In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv(r'C:\Users\SHYAM SASHANK\OneDrive\Desktop\Data_Science\Assginment_CSV\Fraud_check.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [4]:
df1=pd.get_dummies(df)
df1

,Taxable.Income,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,68833,50047,10,1,0,0,0,1,0,1
1,33700,134075,18,0,1,1,0,0,0,1
2,36925,160205,30,1,0,0,1,0,0,1
3,50190,193264,15,0,1,0,0,1,0,1
4,81002,27533,28,1,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
595,76340,39492,7,0,1,1,0,0,0,1
596,69967,55369,2,0,1,1,0,0,0,1
597,47334,154058,0,1,0,1,0,0,0,1
598,98592,180083,17,0,1,0,1,0,1,0


In [5]:
df1.isnull()

,Taxable.Income,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
595,False,False,False,False,False,False,False,False,False,False
596,False,False,False,False,False,False,False,False,False,False
597,False,False,False,False,False,False,False,False,False,False
598,False,False,False,False,False,False,False,False,False,False


In [6]:
x=df1.drop(columns="Taxable.Income")
x.head()

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
0,50047,10,1,0,0,0,1,0,1
1,134075,18,0,1,1,0,0,0,1
2,160205,30,1,0,0,1,0,0,1
3,193264,15,0,1,0,0,1,0,1
4,27533,28,1,0,0,1,0,1,0


In [7]:
y=df1[["Taxable.Income"]]
y.head()

,Taxable.Income
0,68833
1,33700
2,36925
3,50190
4,81002


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.3, random_state=20)

In [10]:
X_train

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
325,25779,16,1,0,0,0,1,0,1
553,26884,13,1,0,0,0,1,0,1
582,32907,12,0,1,0,1,0,0,1
488,76718,10,0,1,0,0,1,0,1
496,59382,5,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
218,38091,19,1,0,0,1,0,1,0
223,192297,17,0,1,0,1,0,0,1
271,183682,20,1,0,0,0,1,1,0
474,80729,0,0,1,1,0,0,1,0


In [11]:
X_test

,City.Population,Work.Experience,Undergrad_NO,Undergrad_YES,Marital.Status_Divorced,Marital.Status_Married,Marital.Status_Single,Urban_NO,Urban_YES
493,103226,29,1,0,0,1,0,1,0
172,52819,23,1,0,0,1,0,0,1
352,72115,16,1,0,1,0,0,0,1
506,111105,8,1,0,0,0,1,0,1
595,39492,7,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...
508,195357,19,1,0,0,0,1,1,0
476,183057,7,1,0,0,0,1,0,1
475,36081,12,1,0,0,0,1,0,1
235,87541,9,1,0,1,0,0,1,0


In [12]:
Y_train

,Taxable.Income
325,94013
553,91462
582,84931
488,86883
496,72151
...,...
218,57794
223,38374
271,42254
474,99128


In [13]:
Y_test

,Taxable.Income
493,17183
172,13068
352,15627
506,23884
595,76340
...,...
508,46002
476,79478
475,35868
235,77735


In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
model = RandomForestClassifier(n_estimators=100, random_state=42)

In [16]:
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [17]:
y_pred_train=model.predict(X_train)
y_pred_train

array([94013, 91462, 84931, 86883, 72151, 67628, 76700, 71238, 20109,
       57445, 30468, 92426, 55308, 68911, 45706, 44034, 93733, 55299,
       76992, 70743, 31721, 41344, 70645, 78963, 72115, 86958, 41395,
       57402, 54747, 91488, 34475, 78969, 51802, 80239, 59440, 54638,
       32662, 97980, 77312, 32786, 51028, 14422, 90444, 46955, 36532,
       48081, 75585, 95088, 79869, 16992, 48169, 43865, 10987, 29222,
       36317, 99307, 82625, 59243, 22773, 22159, 62365, 56628, 86079,
       12659, 95145, 26101, 12011, 77367, 56974, 59860, 13571, 14398,
       91220, 36457, 78400, 33356, 56501, 89277, 71164, 93364, 77511,
       68617, 64614, 28904, 75324, 46629, 98738, 32483, 26793, 86652,
       43980, 98334, 13747, 73188, 24370, 39144, 26972, 14912, 90945,
       72268, 62998, 36239, 34833, 56129, 36890, 98433, 41641, 75170,
       71297, 11804, 60789, 59227, 81378, 31085, 41117, 31417, 64225,
       10379, 28764, 68756, 70298, 22187, 32905, 47364, 97453, 63710,
       50777, 27081,

In [18]:
y_pred_test=model.predict(X_test)
y_pred_test

array([94413, 78400, 87348, 34833, 64320, 74010, 81002, 98416, 64614,
       43018, 86652, 31721, 26101, 71238, 54126, 38374, 90910, 87348,
       33614, 14398, 18888, 70645, 18572, 15491, 68696, 64437, 62998,
       29916, 19649, 21696, 11794, 10870, 94413, 50348, 28904, 73620,
       14300, 27698, 55299, 63912, 98240, 12470, 41117, 71297, 41545,
       94418, 79373, 59689, 99307, 40220, 46955, 87348, 70526, 24541,
       31699, 96355, 39144, 48392, 78963, 81536, 61063, 62426, 99307,
       36532, 63912, 70743, 33215, 83061, 56628, 44034, 18032, 90910,
       42679, 98592, 59615, 84557, 52891, 33116, 10735, 90910, 42507,
       63543, 63912, 54638, 47565, 69869, 46955, 14422, 98738, 84429,
       23075, 31721, 93659, 70572, 77511, 16690, 69018, 10379, 50777,
       68617, 21016, 38183, 71357, 63710, 32948, 68756, 58451, 84845,
       42254, 36239, 13747, 71238, 41344, 84775, 36532, 41641, 11794,
       92426, 91545, 40220, 50242, 36239, 95088, 97453, 90444, 33215,
       17962, 12659,

In [19]:
from sklearn.metrics import classification_report

print(classification_report(y_pred_test,Y_test))

              precision    recall  f1-score   support

       10348       0.00      0.00      0.00       0.0
       10379       0.00      0.00      0.00       1.0
       10455       0.00      0.00      0.00       0.0
       10735       0.00      0.00      0.00       1.0
       10870       0.00      0.00      0.00       1.0
       11794       0.00      0.00      0.00       2.0
       11865       0.00      0.00      0.00       0.0
       12470       0.00      0.00      0.00       2.0
       12514       0.00      0.00      0.00       0.0
       12659       0.00      0.00      0.00       1.0
       12682       0.00      0.00      0.00       0.0
       13068       0.00      0.00      0.00       0.0
       13747       0.00      0.00      0.00       1.0
       14300       0.00      0.00      0.00       1.0
       14310       0.00      0.00      0.00       0.0
       14398       0.00      0.00      0.00       1.0
       14422       0.00      0.00      0.00       1.0
       15296       0.00    

In [20]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(Y_train, y_pred_train))

Accuracy: 1.0


In [21]:
from sklearn.metrics import confusion_matrix

print("\nConfusion Matrix:\n", confusion_matrix(Y_train, y_pred_train))


Confusion Matrix:
 [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [22]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
num_trees = 200
#max_features = 3
kfold = KFold(n_splits=10, random_state=7, shuffle=True) #Bootstrap

model = RandomForestClassifier(n_estimators=num_trees,max_depth=5,  min_samples_leaf=5,max_features='sqrt')
results = cross_val_score(model, x, y, cv=kfold)
print(results.mean())

0.0


In [23]:
#AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier

kfold = KFold(n_splits=10, random_state=7,shuffle=True) 
model1 = AdaBoostClassifier(n_estimators=100, random_state=7)
results = cross_val_score(model1, x, y, cv=kfold)
print(results.mean())


0.0


In [24]:
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y_train = le.fit_transform(Y_train)

In [28]:
model = XGBClassifier(n_estimators=90,max_depth=3)
model.fit(X_train, Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=90, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [33]:
y_pred_test = model.predict(X_test)
predictions = [round(value) for value in y_pred_test]
predictions

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 237,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 237,
 237,
 0,
 0,
 237,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 0,
 237,
 0,
 0,
 0,
 0,
 0,
 0,
 237,
 0,
 0,
 237,
 0,
 0,
 237,
 237,
 0,
 0,
 237]

In [35]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 0.00%


In [36]:
import lightgbm as lgb
d_train = lgb.Dataset(X_train, label=Y_train)

In [37]:
params = {}
params['learning_rate'] = 0.002, # 0.1,0.3
params['boosting_type'] = 'gbdt' # dart
params['objective'] = 'binary'
params['metric'] = 'binary_logloss'
params['sub_feature'] = 0.5 
params['num_leaves'] = 10
params['min_data'] = 50
params['max_depth'] = 10

In [38]:
params

{'learning_rate': (0.002,),
 'boosting_type': 'gbdt',
 'objective': 'binary',
 'metric': 'binary_logloss',
 'sub_feature': 0.5,
 'num_leaves': 10,
 'min_data': 50,
 'max_depth': 10}

In [39]:
clf = lgb.train(params, d_train, 1400)

[LightGBM] [Info] Number of positive: 419, number of negative: 1
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001819 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 186
[LightGBM] [Info] Number of data points in the train set: 420, number of used features: 9
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.997619 -> initscore=6.037871
[LightGBM] [Info] Start training from score 6.037871
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[

[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No f

In [40]:
y_pred = clf.predict(X_test)

In [41]:
predictions = [round(value) for value in y_pred]

In [42]:
accuracy = accuracy_score(Y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 0.00%
